// Generated by https://quicktype.io

export interface Orden {
    ott?:               string;
    descripcion?:       string;
    nroOc?:             string;
    estado?:            string  //Estado;
    etapaOtt?:          string; //EtapaOtt;
    areaResponsable?:   string; //AreaResponsable;
    personResponsable?: string  //PersonResponsable;
    fecRecepcion?:      string;
    usrCreador?:        string  //PersonResponsable;
}

export enum AreaResponsable {
    AlmacénElAlto = "Almacén El Alto",
}

export enum Estado {
    Anulado = "Anulado",
    Cerrado = "Cerrado",
}

export enum EtapaOtt {
    Registrado = "Registrado",
}

export enum PersonResponsable {
    Llc = "LLC",
}
