// Generated by https://quicktype.io

export interface Trafo {
  NroCIA:           string;
  NroSerie:         string;
  Marca:            string;
  Modelo:           string;
  PotNominal:       string;
  Fabricante:       string;
  Tipo_Fase:        string;
  estadoTrafo:      string;
  Ubicacion_Actual: string;
  Nro_OTT:          string;
  Responsable:      string;
}



// {
//   "NroCIA": "1119",
//   "NroSerie": null,
//   "Marca": "OTRO",
//   "Modelo": null,
//   "PotNominal": "200.00",
//   "Fabricante": "OTRO",
//   "Tipo_Fase": "Trifásico",
//   "estadoTrafo": null,
//   "Ubicacion_Actual": "",
//   "Nro_OTT": "00256/2013",
//   "Responsable": ""
// }
