  // Generated by https://quicktype.io

  export interface User {
    id:          string;
    username:    string;
    lastname:    string;
    role:        string;
    perfil:      string;
    perfil_desc: string;
  }
