// Generated by https://quicktype.io

export interface Trafo {
  //id:                number;
  cia?:              string;
  serie?:            string;
  marca?:            string;
  modelo?:           string;
  kvc?:              string;
  fabricante?:       string;
  propietario?:      string;
  tipoFase?:         string;
  estadoTrafo?:      string;
  ubicacionActual?:  string;
  ott?:              string;
  responsable?:      string;
}


// {
//   "NroCIA": "1119",
//   "NroSerie": null,
//   "Marca": "OTRO",
//   "Modelo": null,
//   "PotNominal": "200.00",
//   "Fabricante": "OTRO",
//   "Tipo_Fase": "Trifásico",
//   "estadoTrafo": null,
//   "Ubicacion_Actual": "",
//   "Nro_OTT": "00256/2013",
//   "Responsable": ""
// }
